### ISSUE TITLE
Regarding the Lightroom Script

### ISSUE THREAD

**Issue by NadavZilberman** [minhmanho/deep_preset#4]
Hello!
I'm trying to apply the presets to the photos using the script you provided and the SDK guide, but having some problems (moslty errors in the lua code.)
Can you please publish little more details on how to make this script work?

(In particular: the error I get now in Lightroom is "Info.lua: 1: attempt to index global 'LrApplication' (a nil value)")

Thanks a lot

**Comment by minhmanho** [comment]
Hi,

Yes, sure. I'm working on the tutorial.
I'm not sure about your error.
Could you please elaborate it with screenshots?

**Comment by NadavZilberman** [comment]
> 

Hi, sorry for the delay! Thanks for your answer.

Screenshot:
![lua_error](https://user-images.githubusercontent.com/48512206/147855885-0246a116-2ac5-4d61-96c2-767e4fc17637.jpg)
 
I believe it refers to the first line of the code

Thank you

**Comment by minhmanho** [comment]
Hi @NadavZilberman,

I'm really sorry for the late reply.
Here is the retouch API with a JSON Preset "2" I just made it.
https://drive.google.com/file/d/1qgoZ4Wi3d8Acj_iSE5oDXoLL-UQvIFW1/view?usp=sharing

Steps are as follows:
1. Add the plug-in folder and load plug-in
2. Select all photos in the library
3. Library -> Plug-in Extras -> Apply JSON Settings API -> Pick a JSON preset file
![image](https://user-images.githubusercontent.com/24385510/150457282-6290b463-222b-4252-99c9-46e67b7ff590.png)
4. Then, Done. Your photos will be retouched automatically.

I hope it is still useful.
Best,
