### ISSUE TITLE
Hello, how can I train this network structure,Thank you

### ISSUE THREAD

**Issue by ZzzTD** [minhmanho/deep_preset#7]

**Comment by minhmanho** [comment]
Hi, honestly, I am unable to publish the training code but I can share its ugly version. Please leave your email here.

**Comment by ZzzTD** [comment]
@minhmanho Thank you for your reply. This is my email. Thank you。zzztd0809@gmail.com

**Comment by minhmanho** [comment]
Great! Sent.

**Comment by zjben** [comment]
> Hi, honestly, I am unable to publish the training code but I can share its ugly version. Please leave your email here.

Hi minhmanho, can you please share the training code to me? My email is zjsist@gmail.com. Thank you!

**Comment by minhmanho** [comment]
@zjben Hi, please find it at https://github.com/minhmanho/deep_preset/tree/master#regarding-the-training-code

**Comment by zjben** [comment]
> @zjben Hi, please find it at https://github.com/minhmanho/deep_preset/tree/master#regarding-the-training-code

Thx!
