### ISSUE TITLE
About Training code

### ISSUE THREAD

**Issue by lionking6792** [minhmanho/deep_preset#8]
Hello, cause there is no training code available publicly, can I get the code of them via e-mail like previous closed issue? (little bit messy one is OK for me!)
also, I mailed to you about it! Plz, check the mail and reply to me if u r possible!

Thx for  your appreciation!

**Comment by minhmanho** [comment]
Hi,

Thank you for being interested in my work.
I shared it via your email.
It seems everyone is interested in the training code; I will consider this for my future projects.

Thanks,
